### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by neheller** [danielguterding/pytricubic#3]
`tricubic.tricubic()` seems to leak memory when called repeatedly. The only way I was able to work around it was calling it in a subprocess and joining when I no longer need the interpolator. Any idea why this might be happening? 

Code to reproduce issue:
```python3
import gc

import numpy as np 
import tricubic


def interp(X):
    ip = tricubic.tricubic(list(X), list(X.shape))

    # Added to try to deallocate memory
    del ip
    gc.collect()


if __name__ == "__main__":
    X = np.random.rand(100, 100, 100)
    for i in range(1000):
        interp(X)
```

Code that doesn't have issue: 
```python3
from multiprocessing import Process

import numpy as np 
import tricubic


def interp():
    X = np.random.rand(100, 100, 100)
    ip = tricubic.tricubic(list(X), list(X.shape))


if __name__ == "__main__":
    for i in range(1000):
        p = Process(target=interp)
        p.start()
        p.join()
```

**Comment by danielguterding** [comment]
Thank you for bringing this to my attention. The cause was a classic memory leak due to a missing destructor. I added the destructor in commit d61112680970663ffb8bb6963b4081b1d4ab111c. I will push the new version to pip soon.
