### ISSUE TITLE
Link to original paper

### ISSUE THREAD

**Issue by dratchkov** [danielguterding/pytricubic#6]
Love the library.

Original paper is freely available on late Prof Marsden's page here:
http://www.cds.caltech.edu/~marsden/bib/2005/08-LeMa2005/LeMa2005.pdf

Would be super cool to add it to the README.

**Comment by danielguterding** [comment]
Thank you for the link and your kind words. I added the link to the README as you suggested.

**Comment by dratchkov** [comment]
Thanks!
