### ISSUE TITLE
installation/setup error

### ISSUE THREAD

**Issue by adills** [danielguterding/pytricubic#9]
Lekien provided a great method, so thank for creating a python implementation.  I am having trouble installing it via pip.  (I actually use pipenv within a specific environment.). But I get get a failure when trying to install it.  Have you tried to install it lately with newer versions of things.  

My Pipfile:
[packages]
scipy = "*"
matplotlib = "*"
cmake = "*"

[dev-packages]

[requires]
python_version = "3.11"
python_full_version = "3.11.6"

at about line 25 within the attached file containing the error output it says,
python setup.py bdist_wheel did not run successfully.
[pipenv.exceptions.InstallError]:   │ exit code: 1

Any help to get me into using the tricubic would be greatly appreciated. 
Thank you,
--Andy
[tricubic_install_error.txt](https://github.com/danielguterding/pytricubic/files/14502787/tricubic_install_error.txt)

**Comment by danielguterding** [comment]
Thank you for bringing this problem to my attention. I can reproduce the error with Python 3.11. I will try to find a solution.

**Comment by adills** [comment]
sounds good.  thank you.

--Andy

*Responsibility * Relator * Learner * Achiever * Analytical*

**Comment by danielguterding** [comment]
I created a new version 1.0.4 of tricubic, which should be compatible with Python 3.11. FYI the problem was in the dependency pybind11.

Please test the new version and let me know whether it works for you.

**Comment by danielguterding** [comment]
@adills Does the new version work for you? Can I close this issue?

**Comment by adills** [comment]
Thank you @danielguterding 
The installation was successful and the example and unit test ran fine.
Note: I did not install cmake, only numpy and tricubic. 

********
Details:
********
** INSTALL TRICUBIC
```
% pipenv install tricubic
Installing tricubic...
Resolving tricubic...
Added tricubic to Pipfile's [packages] ...
✔ Installation Succeeded
Pipfile.lock not found, creating...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
✔ Success!
Locking [dev-packages] dependencies...
Updated Pipfile.lock (e579de5bfb1f7c3c7d48c95aad7822e47739c7083f999626cf14b818d2fe73a7)!
Installing dependencies from Pipfile.lock (fe73a7)...
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
```

** INSTALL NUMPY
```
% pipenv install numpy
Installing numpy...
Resolving numpy...
Added numpy to Pipfile's [packages] ...
✔ Installation Succeeded
Pipfile.lock (fe73a7) out of date, updating to (8ff144)...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
✔ Success!
Locking [dev-packages] dependencies...
Updated Pipfile.lock (e9004f3793dc3236ff1055a7f60942947c393aa42cf3d6d1ad6575d34d8ff144)!
Installing dependencies from Pipfile.lock (8ff144)...
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
```

** CHECK EXAMPLE
`% pipenv run python example.py`
(printing 'res' after the loop, gave: 4.077790673619226

** CHECK UNIT TEST
```
% pipenv run python simple_test.py 
...
----------------------------------------------------------------------
Ran 3 tests in 0.001s

OK
```
